#cloud-config
output: { all: "| tee -a /var/log/cloud-init-output.log" }
write_files:
-   content: ${platform_id_rsa}
    encoding: base64
    path: /root/platform_id_rsa
    permissions: '0600'
runcmd:
 - mkdir -p /home/${bastion_ssh_user}/.ssh
 - cp /root/platform_id_rsa /home/${bastion_ssh_user}/.ssh/id_rsa
 - chown ${bastion_ssh_user}:${bastion_ssh_user} /home/${bastion_ssh_user}/.ssh/id_rsa
