#cloud-config
locale: ja_JP.UTF-8

rh_subscription:
  username: ${rhn_username}
  password: '${rhn_password}'
  auto-attach: False
  add-pool: [ '${rh_subscription_pool_id}' ]
write_files:
-   content: ${platform_id_rsa}
    encoding: base64
    path: /root/platform_id_rsa
    permissions: '0600'
runcmd:
 - subscription-manager repos --disable="*"
 - yum-config-manager --disable \*
 - subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ansible-2.6-rpms"
 - subscription-manager repos --enable="rhel-7-server-ose-${openshift_major_version}-rpms"
 - yum -y install openshift-ansible atomic-openshift-clients vim
 - curl -L -o /usr/local/bin/ocinventory https://github.com/literalice/openshift-inventory-utils/releases/download/v0.1/ocinventory_unix
 - chmod +x /usr/local/bin/ocinventory
 - chown ${bastion_ssh_user}:${bastion_ssh_user} /root/platform_id_rsa
 - mkdir -p /home/${bastion_ssh_user}/.ssh
 - mv /root/platform_id_rsa /home/${bastion_ssh_user}/.ssh/id_rsa
