#cloud-config
output: { all: "| tee -a /var/log/cloud-init-output.log" }
write_files:
-  content: |
    #!/bin/bash -ex
    REGION=`curl -s http://169.254.169.254/latest/meta-data/local-hostname | cut -d '.' -f2`
    export AWS_DEFAULT_REGION=$${REGION}
    INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
    for ALLOC_ID in `aws ec2 describe-addresses --filter "Name=domain,Values=vpc" "Name=tag:Role,Values=master" "Name=tag:kubernetes.io/cluster/${platform_name},Values=owned" | /usr/local/bin/jq '.Addresses[].AllocationId' | cut -d '"' -f 2`
    do
      aws ec2 associate-address --instance-id $${INSTANCE_ID} --allocation-id $${ALLOC_ID} --no-allow-reassociation
      STATUS=$$?
      if [ 0 = $${STATUS} ] ; then
        exit 0
      fi
    done
   path: /root/arrocate-eip.sh
   permissions: '0700'
runcmd:
 - curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/local/bin/jq
 - curl -kL https://bootstrap.pypa.io/get-pip.py | python
 - pip install awscli --upgrade
 - sh /root/arrocate-eip.sh
 - touch /root/.provisioning-finished && chmod 644 /root/.provisioning-finished
