#cloud-config
locale: ja_JP.UTF-8
write_files:
-   content: ${platform_id_rsa}
    encoding: base64
    path: /root/platform_id_rsa
    permissions: '0600'
runcmd:
 - yum -y install git vim httpd-tools java-1.8.0-openjdk-headless python-passlib patch
 - yum -y update
 - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
 - sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
 - yum -y --enablerepo=epel install ansible pyOpenSSL
 - git clone https://github.com/openshift/openshift-ansible
 - mkdir -p /usr/share/ansible/
 - mv openshift-ansible /usr/share/ansible/
 - cd /usr/share/ansible/openshift-ansible && git checkout release-${openshift_major_version}
 - curl -L -o /usr/local/bin/ocinventory https://github.com/literalice/openshift-inventory-utils/releases/download/v0.1/ocinventory_unix
 - chmod +x /usr/local/bin/ocinventory
 - chown ${bastion_ssh_user}:${bastion_ssh_user} /root/platform_id_rsa
 - mkdir -p /home/${bastion_ssh_user}/.ssh
 - mv /root/platform_id_rsa /home/${bastion_ssh_user}/.ssh/id_rsa
