OSEv3:
  children:
    masters:
      hosts:
    etcd:
      hosts:
    nodes:
      hosts:
  vars:
    ansible_user: ${ansible_user}
    ansible_become: true
    openshift_deployment_type: ${openshift_deployment_type}
    openshift_release: "${openshift_major_version}"
    openshift_repos_enable_testing: ${openshift_repos_enable_testing}
    openshift_cluster_admin_users: ${openshift_cluster_admin_users}
    openshift_master_identity_providers:
      - name: 'test_identity_provider'
        login: true
        challenge: true
        kind: 'AllowAllPasswordIdentityProvider'
    os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
    openshift_disable_check: 'disk_availability,memory_availability'
    openshift_master_cluster_hostname: master.${platform_name}.internal
    openshift_master_cluster_public_hostname: ${platform_domain}
    openshift_master_default_subdomain: ${platform_domain}
    openshift_cloudprovider_kind: aws
    openshift_clusterid: ${platform_name}
    openshift_logging_install_logging: true
    openshift_logging_es_pvc_dynamic: true
    openshift_logging_es_memory_limit: 512M
    openshift_metrics_install_metrics: true
    openshift_metrics_cassandra_storage_type: dynamic
    openshift_master_api_port: 443
    openshift_master_console_port: 443
